import "./globals.css";
import TonProvider from "@/modules/TonProvider/TonProvider";
import Header from "@/modules/Header/Header";
import { HeaderProvider } from './../modules/context';

export const metadata = {
  title: "test-delaenit-ex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
      <TonProvider>
      <HeaderProvider>
        <Header/>
        {children}
        </HeaderProvider>
      </TonProvider>
      </body>
    </html>
  );
}
